### ISSUE TITLE
RSS doesn't refresh

### ISSUE THREAD

**Issue by jondor** [senlin/so-dashboard-feed-widget#10]
Maybe I'm missing something, but the feed got a second item, but the plugin still shows only one. Reload, forced reload, empty cache and reload.. nothing seems to help?!

**Comment by so-watcher** [comment]
Have you tried a different feed yo see if that works at all? 
Sent from my Xiaomi
On jondor <notifications@github.com>, Jun 12, 2015 5:39 AM wrote:Maybe I'm missing something, but the feed got a second item, but the plugin still shows only one. Reload, forced reload, empty cache and reload.. nothing seems to help?!

**Comment by jondor** [comment]
I tried nu.nl's algemene rss feed which updates often.. Also no update.. But I think I traced the issue down to https://codex.wordpress.org/Plugin_API/Filter_Reference/wp_feed_cache_transient_lifetime

fetch_feed has a default caching timeout of 12 hours which explains why more busy newsfeeds don't seem to update.. 60 min. or as configuration option would make more sense

**Comment by senlin** [comment]
Yeah, that makes sense. I originally developed the plugin to show clients updates from their "webmaster" and as such the long transient does not cause any issues. 

I think it is a good idea to make the transient a configurable variable. 

The coming two weeks i am busy, but after that i will update the plugin. Thanks for the idea!
