### ISSUE TITLE
Dashboard Feed Widget

### ISSUE THREAD

**Issue by eProperty-pk** [senlin/so-dashboard-feed-widget#12]
How can I add multiple feeds from different sites. It only allow to add one feed. Is possible to add more then one feed?

**Comment by senlin** [comment]
It is not possible with the plugin to add feeds from more than one URL. 

The only way to do that is to use an aggregator that collects feeds from different sites and then add the feed URL of that aggregator.

**Comment by eProperty-pk** [comment]
Ok thanks good idea
