### ISSUE TITLE
Backlink to page where the RSS is generated

### ISSUE THREAD

**Issue by jondor** [senlin/so-dashboard-feed-widget#9]
A wish-request: Would it be possible to add two fields to the options and presentation, with a title and an url to be presented under the rss output?

As I use the widget for the rss of a questions and answers system, I would like to add a link to where they can ask an question them selfs.
But it would also be useful to direct the readers to the archive with older articles.

**Comment by so-watcher** [comment]
Thanks for your feature request, we will take it under consideration 
Sent from my Xiaomi
On jondor <notifications@github.com>, Jun 11, 2015 6:42 PM wrote:A wish-request: Would it be possible to add two fields to the options and presentation, with a title and an url to be presented under the rss output?

As I use the widget for the rss of a questions and answers system, I would like to add a link to where they can ask an question them selfs.
But it would also be useful to direct the readers to the archive with older articles.

**Comment by senlin** [comment]
Can you please make a mockup of what you mean  exactly? It's not entirely clear from the description. 
You could also hack the plugin, because it sounds like a very specific use case. What I  mean is how do you see what you want to be beneficial for other users of the plugin?

**Comment by jondor** [comment]
It's not such a weird request..;-) See f.e. one of my non-wordpress sites (http://ondernemen.enschede.nl/) the news on the frontpage includes a link to the "archive > ", which is in this case the RSS channel link.  Just a way to get back to the page with all the news.  And it would be nice if the title of this link would be configurable..

**Comment by senlin** [comment]
I think the issue is that you compare frontend behaviour with backend behaviour. What would be the reason to send people from the WordPress Dashboard to a different site altogether? I don't get that.

**Comment by jondor** [comment]
Guess it depends on what you use it for. Say it's a feed of a discussionforum. You see a reaction and want to read the rest of the thread. A changelog with new features and you see only the last 3 (because of the setting, need some space for other things too..) I want to see the whole list. 
My point is that there are many usecases where the stream goes fast and where the last x messages is just enough to make one thing: I have to see the rest too.. 

Anyhow, if you don't see the point, no problem. For me it was more that it's easier to use or add to an existing plugin than to create one that does almost the same, but not completely.. 
Glad I could help out with the rss caching..;) Thanks!

**Comment by senlin** [comment]
Will not implement this as this is too far away from what the plugin is intended to do. Thanks for your input though :+1:
